### ISSUE TITLE
Choose descriptive title and rename study top-level container

### ISSUE THREAD

**Issue by sbesson** [IDR/idr0045-reichmann-zygotespindle#9]
Until IDR 0.5.0, the naming scheme for submissions was `idr<accession>-<name>-<title>` where `accession` is a 4 digit accession number, `name` is the last name of the first author on the reference publication and `title` is a short description of the study. The difficulty associated with associating titles with every study as well as the impact on the length of the containers in the UI led us to drop this suffix for `idr0045`.

As per last Monday's IDR meeting, this change has some downsides for the [Human Protein Atlas](https://github.com/IDR/idr0043-uhlen-humanproteinatlas) study where the `title` refers to a well-established consortium/project and is probably the most informative.

For IDR 0.5.2, the proposal was to revert the change above and unify all studies back to the `idr<accession>-<name>-<title>` scheme. This means a representative title needs to be chosen for this study.

Beyond IDR 0.5.2, we can look into revisiting this naming scheme and the cost/benefit of doing so.

**Comment by francesw** [comment]
My suffix suggestions for idr0045-reichmann are zygotespindle or spindlezygote.  I think spindlezygote looks better.

Was tempted by zygotelightsheet or spindlelightsheet, but I believe we also have confocal images in this dataset.
